### ISSUE TITLE
Sync different folders/modpacks with server and client

### ISSUE THREAD

**Issue by Guerdi** [Skidamek/AutoModpack#110]
Hello !

I have a lot of clients only mods that improve graphics, visual performance, add sounds, animations, etc… And I don't want the server to take resources to load them just to distribute them to clients.

Similarly, I don't want clients to load server-only mods from my server, even though mods automatically filter out server-only mods in fact most server-only mods are *optional* on the client and would still be loaded.
(In my case Carpet or Taterzens are server-only but add animations/translations if present on the client and so will still download on client).

The solution would be, I think, to allow a different folder to be synced on the server and which the server would not use in its normal operation.
It could be in the folder where the configs are present, something like:
/automodpack/syncfile/config/
/automodpack/syncfile/mods/
/automodpack/syncfile/resourcepacks/
/automodpack/syncfile/shaderpacks/

And so on…

I think it's pretty obvious, but I still allow myself to simply suggest allowing updates with modpacks downloadable on modrinth ;)

The mod has a lot of potential but currently, and without the suggested changes, I'm afraid it won't really work for me and I don't believe I'm the only one.

Bravo for all the work already done, and I hope you will continue to improve and maintain this mod!

**Comment by Skidamek** [comment]
wait isn't it already done? in /automodapck/ folder you can add whatever you want to modpack and it won't be loaded by server, also there is in config syncedFiles list to which you can add folders without coping them to /automodpack/ folder and also there is excludeSyncedFiles list in config which allows you to exclude some files from adding to modpack...

**Comment by Guerdi** [comment]
The default path is automatically the same on the client as on the server, so if I put mods in the automodpack/mods folder so the server doesn't need to load it the client will also have them in automodpack/mods and not won't charge either.

For the client to load the mods, they would have to be downloaded in the /mods folder, but for that they would also have to be in this folder on the server and the server would load them.

The solution would be to be able to indicate in the config "this "automodpack/mods" folder on the server corresponds to this "/mods" folder on the client".

**Comment by Skidamek** [comment]
I am confused how did you get to the conclusion that servers /automodpack/host-modpack/mods != on client /mods/ because it does.
I mean client collects whole modpack from server to /automodpack/modpacks/<>/ it doesn't matter if it is on server in /mods/ or /automodpack/host-modpack/mods/ client need as you said have mods inside /mods/ folder yes! So it automatically copies mods to that folder. (Actually it is possible to don't need to copy every file but it is really hard to make it work on every device)


On server /automodpack/host-modpack/ and / corresponds to exactly /.minecraft/  on official Mojang launcher

It needs to have modpack downloaded in different directory to manage it and to know what to delete if you deleted something

**Comment by Skidamek** [comment]
I think that's because of your issue #117 try solve it first and then you will see :)
