### ISSUE TITLE
A way to disable the mod adding the host port to the end of the download link. 

### ISSUE THREAD

**Issue by Norteous** [Skidamek/AutoModpack#149]
### Motivation

When I was setting this up on my server I was unable to port forward it in a way that would work. I was using ngrok and setting the tcp tunnel as the host local ip. Since the ngrok tunnel was forwarding the host port and the mod was adding the same host port on the end, it just gave me an error when my friends tried to join.

### Description

Have a way to toggle the host port being added at the end of the download link.

### Other information

I also might have just been doing it wrong, if so I am sorry for wasting your time. Also if I am using any terms wrong I am also sorry.

**Comment by Skidamek** [comment]
Hmm, alright, you probably already have forwarded the same IP address to just connect to Minecraft server so you probably just need to type ngrok url without http/s at start to the `hostIp` in automodpack server config

**Comment by Norteous** [comment]
I'm not sure I fully understand.

**Comment by Skidamek** [comment]
Ah alright gotcha gonna add this in next update probably today

**Comment by Norteous** [comment]
Thank you for your help.

**Comment by Skidamek** [comment]
Which loader are you using?

**Comment by Norteous** [comment]
Fabric 1.20.1

**Comment by Skidamek** [comment]
Alright done, code is on [external-proxies](https://github.com/Skidamek/AutoModpack/tree/external-proxies) branch.
To use, change the AutoModpack jars on server and client to [this](https://github.com/Skidamek/AutoModpack/files/12209088/automodpack-mc1.20.1-fabric-3.4.4-SHAPSHOT.zip) (zipped because github restrictions, so unzip)

And in server config set reverseProxy to `true`
Forward port from `hostPort` to ngrok via `http` not `tcp` protocol
Copy whole ngrok url with https:// to `externalModpackLink` in config
Restart the server and everything should work.

**Comment by Norteous** [comment]
Seems to work! Thank you for your help.

**Comment by Skidamek** [comment]
Great, however I will leave it open until I will merge it to main release probably with full 3.4.4
