### ISSUE TITLE
Says restart to install mods, everytime server boots up even though there is no change

### ISSUE THREAD

**Issue by BumbleTree** [Skidamek/AutoModpack#191]
### Bug description

Everytime the server restarts, it prompts people who join to restart their game to apply downloaded changes (there are none and the changelog is grayed out)

### Steps to reproduce

1. Restart server
2. Join server

### Expected behavior

It to log you on without prompting this

### Actual behavior

It prompts to restart

### Minecraft & Mod Loader versions

1.20.1 from Automodpack fabric installer

### Minecraft launcher

Standard

### Operating system

Windows 11

### AutoModpack version

3.5.2

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by mariobrosmania** [comment]
I Had this issue as well a while ago it was because I had `generateModpackOnStart` set to `true` in the server config Disabling this prevented the mod from making a new manifest every time the server restarts, the update prompt is because your client manifest differs from the servers which is why it asks you to update I believe. If you do decide to change that setting to false make sure you run the command `automodpack generate` in console whenever you add or remove a mod from your modpack.

**Comment by Skidamek** [comment]
Fixed in 4.0.0 beta 1!

**Comment by Kimers** [comment]
hi, apparently the problem has returned again, I ran into it on the automodpack-forge-4.0.0-beta6-1.20.1 version

**Comment by Skidamek** [comment]
@Kimers please create new issue providing more details along side the logs
