### ISSUE TITLE
Mod folder

### ISSUE THREAD

**Issue by Paulinho1235** [Skidamek/AutoModpack#226]
### Motivation

There would be some command that allows you to install it. the mods directly in the mods folder and not in the automodpack folder?

### Description

.Would there be a command that allows you to install it? the mods directly in the mods folder and not in the automodpack folder?

**Comment by Skidamek** [comment]
But why? Does it couse any issues?

**Comment by Skidamek** [comment]
There are reasons why we organize mods to load them from a separate directory:

- It lets us update the modpack when the client just clicked launch button, saving us from restarting the game. Before version 4.0.0, mods were in the default directory. But doing it that way made it hard to reliably remove unwanted mods from the loader, when server updated to a new mod version or deleted some mods. And since windows doesn't really allow doing that, my solution to that was to turn 'unwanted' mods to 'dummy' mods which made it confusing for a lot of people since these mods were still in the folder but just empty) 

- Mods like mine, which load early, are just out of our control because we can't intervene in their loading process. E.g. other mod which uses similar techniques to automodpack could load bunch of other mods/code, even before we can do anything with it.

- Different modpack, different mods. Current approach gives us nice separation. Without that it requires a lot of checking if mods are for sure in correct directory, a lot of moving files when you e.g. have more than one modpack and want to switch. It's just make it slow.

- While it's in theory possible to only use the mods folder, it would require very precise code to unload other mods safely. This approach is unsafe because updates to forge or fabric could just break everything. The most reasonable solution at this point would be to just fork forge/fabric to our needs.

Current approach makes it all cleaner. Since all we need now is to make sure that modpack mods are indeed in /automodpack/modpacks/<modapck> folder. And we can load these mods when we want without doing weird filesystem 'hacks' and hope that it will work. Now we can just load them conditionally which makes it much more reliable. While yes we still touch unsafe exclusive loader code, we don't require that many changes to it.

**Comment by Skidamek** [comment]
I guess I am closing it then
