### ISSUE TITLE
Open to lan working

### ISSUE THREAD

**Issue by petermg** [Skidamek/AutoModpack#238]
### Motivation

I would love for this to be able to work just with direct connections over the lan via the "OPEN TO LAN" option so that no server is required, just two people on the same network playing just on the Minecraft clients connecting as they already do one to the other via "OPEN TO LAN". Would be amazing if this would also work for those instances as well!

### Description

This would make is just as easy for two people on the same LAN using "OPEN TO LAN" to play multiplayer to both sync their mods! This would be AMAZING if this could be added as a feature!

**Comment by Skidamek** [comment]
It is planned, but do note that both clients will still be required to have automodpack installed in the first place

**Comment by Skidamek** [comment]
Yes that's right

**Comment by Skidamek** [comment]
Okay lan connections are working now. Try [this dev build](https://github.com/Skidamek/AutoModpack/actions/runs/9677214729)
The only issue is that mods like essential or e4mc don't work with it. I am not sure but i can guess it is because AutoModpack uses HTTP protocol to host modpack and these mods may allow only packets from minecraft protocol.
However solutions like https://playit.gg/ or https://ngrok.com/ should work since they proxy whole TCP protocol.

**Comment by petermg** [comment]
Awesome! I will try this out soon! Thanks.
