### ISSUE TITLE
server-side mod selector

### ISSUE THREAD

**Issue by TinhoCarrara** [Skidamek/AutoModpack#244]
### Motivation

some mods cause bug if installed on client side

### Description

There are some mods that need to be installed only on the server side as installing them on the client side causes bugs. Is there any way to configure which mods should be downloaded and which not via the server?

**Comment by Skidamek** [comment]
Yes, see [`syncedFiles`](https://github.com/Skidamek/AutoModpack/wiki/Modpack-Creation#two-ways-of-adding-content-to-the-modapck) by default it includes all mods (files ending with .jar to the mod pack). Using `!` you can exclude any of them.

**Comment by Skidamek** [comment]
Or second option remove everything from syncedFiles, and place everything you want (without these server side mods) to into `~/automodpackhost-modpack/main/` directory. But that's then requires changing files there everytime you change them in standard mods folder, otherwise in the modpack would be different version of the mod than on the server.
