### ISSUE TITLE
[1.19.2 Fabric/Quilt 3.0.1] Mod Load Order Issues and Client Restrictions

### ISSUE THREAD

**Issue by JLUsr** [Skidamek/AutoModpack#93]
**Describe the bug**
Fabric/Quilted Fabric API and other dependency mods end up having issues with the way/order mods are loaded now.

**To Reproduce**
1. Install something like [`Trinkets`](https://modrinth.com/mod/trinkets) on the server AutoModpack is hosted on.
2. Update AutoModpack on the client by connecting to the server AutoModpack is hosted on.
3. Install something like [`Trinkets Curios Theme`](https://modrinth.com/mod/trinkets-curios-theme) on the client connecting to the server AutoModpack is hosted on.
4. Attempt to launch the client, you should get something like `Dependency for mod 'trinkets-curios-theme' on trinkets versions [>=3.4.0] (0 valid options, 0 invalid options)`

Even if you install `Trinkets` on the client, the jar gets detected by AutoModpack and as a result, its contents are cleared so that it doesn't attempt to load from the default `/.minecraft/mods/` folder, and the `mods` folder generated by AutoModpack. This also applies to things like Fabric API and Quilted Fabric API making it nearly impossible for the client to use any client-side mods that have dependencies on mods being used by AutoModpack.

**Expected behavior**
Files within the `/.minecraft/mods/` folder should be prioritized over the mods generated by AutoModpack.

**AutoModpack and Minecraft Version you are using (please complete the following information):**
 - Tested on Fabric and Quilt 1.19.2 with AutoModpack 3.0.1

**Additional context**
Let me start by saying that I absolutely love this mod and the intentions behind it. The new 3.0.1 update has a very nice appearance too. I can see that the new system has reduced duplicate files on both the server and the client side of things; however, this has inadvertently caused restrictions on the clients' freedom.

Honestly, I think it might be better to use the old system of having mods generated by AutoModpack be copied into the `/.minecraft/mods/` folder (or add another folder and option in the config to switch between the new, more integrated, system and the old, more segregated, system for managing files/mods/configs and the like). I personally miss the ability to define `[CLIENT] mods` and because of this issue I also haven't been able to test if it's possible to define custom changes to things like the clients `bin` folder or setting up [`global_packs`](https://modrinth.com/mod/globalpacks) resources for the client to use (though this seems possible based on the `syncedFiles` parameter in the config).

**Comment by Skidamek** [comment]
looks like i did the best anticheat XD

**Comment by Skidamek** [comment]
Thanks, you got the point, i thought this update maybe a bit controversial one... Well it is what it is.

`[CLIENT] mods` got deleted because it's not longer needed. Now anything put into servers' folder `./automodpack/host-modpack/...` works like previous `[CLIENT] mods`.

I know what can i do to don't need to copy mods to default `./.minecraft/mods/` to make it work.
However having modpack mods in different directory still makes some problems e.g. with relaunching in #87 
I would love to hold modpack files in different folder it just makes it better in many cases, like much easier updates because thanks to that, the old shity delmods.txt could got retired and all modpack mods are in one folder and thanks to that we can easily see that if there is some mod which doesn't exists on server's modpack-content.json got removed from modpack, so we can delete that from dedicated modpack mods folder and don't think of some mixed mods from modpack with default mods like it was before. For sure there could be different solution to make it also work. But solution to having modpack mods in default `./.minecraft/mods/` has much higher chance to broke more things, delete files which shouldn't be deleted etc.

So would be super cool if somebody how knows something about UNIX systems and relaunching jvms/minecraft more than me would help with fixing #87 and then just fixing this issue is easy. Thanks!

**Comment by Skidamek** [comment]
Temporally fixed in 3.0.2, should be ok for time being. I will improve that in future

**Comment by Skidamek** [comment]
Hey, i was thinking about that and i made a decision to remove relauncher and copy mods to main minecraft folder kinda like it was before what do you think about that? This segregation to folders and auto relauncher is cool but due to many issues you having i think would be better to change that, no?
