### ISSUE TITLE
Restart loop after updating to 3.0.1

### ISSUE THREAD

**Issue by TeaJeep** [Skidamek/AutoModpack#95]
Using Automodpack 3.0.1 on 1.19.2, Minecraft keeps getting stuck on a restart loop.  I updated from that pre-release version that was posted in one of the bug reports from a while ago, and then deleted the automodpack directory to clear things out.  After launching the game and downloading the modpack, then restarting the game, it gets stuck in a loop in the background.  There is no indication Minecraft is even running outside of task manager.  

I just kept re-opening latest.log repeatedly until I got the whole thing to show up, since it kept deleting itself from the game restarting.

**Comment by Skidamek** [comment]
Hm weird 
Can you make sure is that these paths are correct?

"C:/Users/tyler/AppData/Local/Packages/Microsoft.4297127D64EC6_8wekyb3d8bbwe/LocalCache/Local/runtime/java-runtime-gamma/windows-x64/java-runtime-gamma/bin/java"

"C:/Users/tyler/AppData/Roaming/.minecraft/profiles/Fabric-1.19.2/automodpack/modpacks/192.168.1.110-30037/mods"

And send please zipped whole automodpack folder with normal Minecraft mods folder (everything from client)

**Comment by TeaJeep** [comment]
The paths look to be correct!  

The normal minecraft mods folder has only latest automodpack and fabric api 0.73.2, which was autodownloaded.  

Here's the whole automodpack folder: https://www.mediafire.com/file/ndjayzwddy5wdzd/AutoModpack.zip/file

**Comment by Skidamek** [comment]
Ok, i see the problem you put mods into `/automodpack/host-modpack/` folder, which means on normal client it will be default minecraft running folder `/.minecraft/`. Mods won't load into modloader from there, but automodpack see that's there are mods because there are, but because there are in wrong folder they can't be loaded and you get stuck in the loop where automodpack checks if they are loaded but they always are not...

To add additional mods to modpack you should put them in server's `/automodpack/host-modpack/mods/` and analogically anything else like e.g. shaderpacks you should put them into `/automodpack/host-modpack/shaderpacks/`, you can create there any folder you want add to modpack.

+ Looks like you have few mods only compatible with quilt, you can't them even use on fabric but most fabric mods should load without problems on quilt i suggest to switch to quilt loader.

**Comment by chitinlink** [comment]
> To add additional mods to modpack you should put them in server's `/automodpack/host-modpack/mods/` and analogically anything else like e.g. shaderpacks you should put them into `/automodpack/host-modpack/shaderpacks/`, you can create there any folder you want add to modpack.

I was trying to set up automodpack yesterday and was having issues -- this wasn't clear in the readme

**Comment by Skidamek** [comment]
> I was trying to set up automodpack yesterday and was having issues -- this wasn't clear in the readme

Thanks for feedback really appreciate that, I will improve that!

**Comment by TeaJeep** [comment]
Oh, that makes a lot more sense, I thought it was weird just dumping the files in there. Thank you!  As for the Quilt mods, those weren't supposed to be there but I must've missed a few at some point, I'll get those removed now then.

**Comment by Skidamek** [comment]
I guess i can close that, if anything is unclear please write message anywhere
